-- AlterTable
ALTER TABLE "Dates" ALTER COLUMN "soatDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "insuranceDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "legalRevisionDate" SET DEFAULT CURRENT_TIMESTAMP;
